In [1]:
import pandas as pd

In [2]:
f = "../../data/estacion_meteorologica.zip"
# f = "../../data/prueba.txt"
estacion = pd.read_csv(f,skiprows=[0,2,3],index_col=0,parse_dates=True)
estacion.I_glo_Avg = estacion.I_glo_Avg.astype(float)
estacion.I_dir_Avg = estacion.I_dir_Avg.astype(float)
del estacion["RECORD"]
estacion.info()

C:\Users\gbv\AppData\Local\Temp\ipykernel_56700\2250284101.py:3: DtypeWarning: Columns (4,5) have mixed types. Specify dtype option on import or set low_memory=False.
  estacion = pd.read_csv(f,skiprows=[0,2,3],index_col=0,parse_dates=True)

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1005267 entries, 2023-05-31 18:59:00 to 2025-04-30 18:05:00
Data columns (total 24 columns):
 #   Column         Non-Null Count    Dtype
---  ------         --------------    -----
 0   BattV          1005267 non-null  float64
 1   PTemp_C        1005267 non-null  float64
 2   I_glo_Avg      1005266 non-null  float64
 3   I_dir_Avg      1005266 non-null  float64
 4   I_dif_Avg      1005267 non-null  float64
 5   I_glo_inc_Avg  1005267 non-null  float64
 6   I_uv_Avg       1005267 non-null  float64
 7   Indice_UV_1    1005267 non-null  float64
 8   Indice_UV_2    1005267 non-null  float64
 9   I_UVA_Avg      1005267 non-null  float64
 10  AirTC_Avg      1005267 non-null  float64
 11  AirTC_Max      1005267 non-null  float64
 12  AirTC_Min      1005267 non-null  float64
 13  AirTC_Std      1005267 non-null  float64
 14  RH             1005267 non-null  float64
 15  RH_Max         1005267 non-null  float64
 16  RH_Min         1005267 non-null  float64
 17  WS_ms_Avg      1005267 non-null  float64
 18  WS_ms_Max      1005267 non-null  float64
 19  WS_ms_Min      1005267 non-null  float64
 20  WS_ms_Std      1005267 non-null  float64
 21  WindDir        1005267 non-null  float64
 22  CS106_PB_Avg   1005267 non-null  float64
 23  Rain_mm_Tot    1005267 non-null  float64
dtypes: float64(24)
memory usage: 191.7 MB

In [3]:
columnas = estacion.columns
Is = [columna for columna in columnas if ("Avg" and "I_") in columna]

Is
irradiancia = estacion[Is]
irradiancia

,I_glo_Avg,I_dir_Avg,I_dif_Avg,I_glo_inc_Avg,I_uv_Avg,I_UVA_Avg
TIMESTAMP,,,,,,
2023-05-31 18:59:00,9.66,21.710,7.391,6.752,0.000,0.367
2023-05-31 19:00:00,9.26,0.000,7.020,6.398,0.000,0.342
2023-05-31 19:01:00,8.83,2.945,6.603,5.985,0.000,0.314
2023-05-31 19:02:00,8.46,3.643,6.262,5.590,0.000,0.293
2023-05-31 19:03:00,8.02,7.574,5.952,5.082,0.000,0.274
...,...,...,...,...,...,...
2025-04-30 18:01:00,41.86,0.435,35.590,46.760,0.003,2.608
2025-04-30 18:02:00,40.71,0.608,35.360,46.280,0.003,2.575
2025-04-30 18:03:00,40.79,0.496,35.180,46.710,0.003,2.563
2025-04-30 18:04:00,41.54,0.560,35.620,47.210,0.003,2.580
2025-04-30 18:05:00,41.83,0.538,35.740,47.700,0.003,2.588

In [4]:
irradiancia.to_csv("../../data/Irradiancia.csv")
irradiancia.to_parquet("../../data/Irradiancia.parquet")